### PR TITLE
Bugfixes

### LINKED ISSUE #3: /dc reset %playername% doesn't display player name in the console feedback
It just says
> DC: Resetting deaths for

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
Fixes #3, #4 and some warnings.
Also updates forge.

### CODE REVIEW

**Comment by iChun** [comment]
OMG stop 😭 I get it my mod is old and broken okay. I wrote it in like an
hour or something many years ago for a friend lol.

**Comment by HoldYourWaffle** [comment]
Yeah I figured it was old. 😅 It isn't as broken as it seems though, just tiny little errors that I noticed while cleaning up the code. The fact that the core functionality actually works perfect is impressive considering your *situation* 😆 

Anyways I'm fixing it because I need it for a server, and it's just plainly against my principles to not report/fix any errors I find. I'm not trying to say you're a horrible coder (you're not), just trying to fix it so others (however few) can use this mod as it's meant to be (not broken 😄). 

I'll keep adding commits to this PR if I find more errors, but I wont create any new issues since I guess that'd be unnecessary torture 😇 

(Keep in mind that #2 is what *really* matters to me, I'm just cleaning all of this up because I want to add [new functionality](https://github.com/HoldYourWaffle/Death-Counter/tree/calibration))

**Comment by HoldYourWaffle** [comment]
Any chance of this getting merged?
Cause I don't really see a reason why not.

**Comment by CrankySupertoonArchive** [comment]
Please, @HoldYourWaffle Can you upload your custom Death Counter to curse, because this seems unmaintainted

**Comment by HoldYourWaffle** [comment]
@CrankySupertoon01 I tried but it was removed.

**Pull request merged**
